version: "3.8"

services:
  remark:
    image: ghcr.io/umputun/remark42:master
    environment:
      - REMARK_URL=https://remark.hyeon.pro
      - SITE=hyeon.pro
      - SECRET=${SECRET}
      - STORE_BOLT_PATH=/srv/var/db
      - BACKUP_PATH=/srv/var/backup
      - DEBUG=true
      - AUTH_GOOGLE_CID=${AUTH_GOOGLE_CID}
      - AUTH_GOOGLE_CSEC=${AUTH_GOOGLE_CSEC}
      - AUTH_GITHUB_CID=${AUTH_GITHUB_CID}
      - AUTH_GITHUB_CSEC=${AUTH_GITHUB_CSEC}
      - ADMIN_PASSWD=q1w2e3!@
      - AUTH_EMAIL_ENABLE=true
      - ADMIN_SHARED_EMAIL=support@hyeon.pro
      - ADMIN_SHARED_ID=${ADMIN_SHARED_ID}
      - AUTH_EMAIL_HOST=smtp.gmail.com
      - AUTH_EMAIL_PORT=587
      - AUTH_EMAIL_FROM=noreply@hyeon.pro
      - AUTH_EMAIL_SUBJ=Remark42
      - AUTH_EMAIL_CONTENT_TYPE=text/html
      - AUTH_EMAIL_TLS=true
      - AUTH_EMAIL_USER=bot.hansanghyeopn@gmail.com
      - AUTH_EMAIL_PASSWD=${APP_PASSWORD}
      - AUTH_EMAIL_TIMEOUT=10s
      - NOTIFY_EMAIL_FROM=remark@hyeon.pro
      - NOTIFY_EMAIL_ADMIN=true
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_TLS=true
      - SMTP=USERNAME=bot.hansanghyeopn@gmail.com
      - SMTP=PASSWORD=${APP_PASSWORD}
    volumes:
      - ./var:/srv/var
    deploy:
      placement:
        constraints:
          - node.hostname == ${HOSTNAME}
      labels:
        - traefik.enable=true
        ## HTTP Routers
        - traefik.http.routers.remark.entrypoints=websecure
        - traefik.http.routers.remark.rule=Host(`remark.hyeon.pro`)
        - traefik.http.routers.remark.tls.certresolver=leresolver
        - traefik.http.services.remark.loadbalancer.server.port=8080

networks:
  default:
    external:
      name: proxy-main
